apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-8phj
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0064-tenant/tkrw-pr712-0075-0064-app/devfile-sample-8phj@sha256:0f5ec74cb23cee42f3d4759449014c084c232f5c9bbbf0dd7c199997c48f0065
        name: my-nodejs
        resources: {}
status: {}
